from typing_extensions import TypedDict


class PlanItem(TypedDict):
    """
    Represents one section of the research plan.
    """
    id: int
    section: str
    objective: str

class ErrorInfo(TypedDict):
    """
    Represents an error generated by any agent.
    """
    agent: str
    message: str

class ResearchState(TypedDict):
    """
    Shared state passed between all LangGraph nodes.
    """
    # User Input
    query: str

    # Planner Output
    plan: list[PlanItem]

    # Supervisor State
    current_plan_index: int

    # Research Agent Output
    research_data: dict[str, str]

    # Summarizer Output
    summary: str

    # Fact Checker Output
    fact_checked_data: dict[str, str]

    # Writer Output
    final_report: str

    # Workflow Errors
    errors: list[ErrorInfo]

    next_step: str